# Generated by Django 4.0.6 on 2022-09-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='LGA',
            new_name='LocalGovernment',
        ),
        migrations.AlterField(
            model_name='registeration',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.gender'),
        ),
    ]
