# Generated by Django 4.0.6 on 2022-09-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_gender_rename_lga_localgovernment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeration',
            new_name='Student',
        ),
    ]
