# Generated by Django 4.0.6 on 2022-09-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_rename_registeration_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Student_class',
            new_name='StudentClass',
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.IntegerField(default=0)),
                ('ca2', models.IntegerField(default=0)),
                ('exam', models.IntegerField(default=0)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.subject')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.term')),
            ],
        ),
    ]
