# Generated by Django 4.0.6 on 2022-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_subject_rename_student_class_studentclass_scoresheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(max_length=200),
        ),
    ]
