# Generated by Django 4.0.6 on 2022-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_alter_student_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_school_if_any',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
